services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: interpol_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" #RabbitMQ'nun mesajlaşma portu
      - "15672:15672" #RabbitMQ yönetim arayüzü portu
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    healthcheck:
      #diğer servislerin RabbitMQ'ya bağlanmadan önce hazır olup olmadığını kontrol etmek için  ekleniyor
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  minio:
    image: minio/minio:latest
    container_name: interpol_minio
    restart: unless-stopped
    ports:
      - "9000:9000"   # API / S3 endpoint
      - "9001:9001"   # Web UI (MinIO Console)
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:16-alpine
    container_name: interpol_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-interpol}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-interpol123}
      POSTGRES_DB: ${POSTGRES_DB:-interpol_db}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data #veriler konteyner silinse bile kalır
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U interpol -d interpol_db" ]
      interval: 5s
      timeout: 3s
      retries: 10

  fetcher:
    #kendi Dockerfile'ından build ediliyor RabbitMQ sağlıklı hale gelince başlatılır
    build:
      context: .
      dockerfile: fetcher/Dockerfile
    container_name: interpol_fetcher
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      INTERPOL_BASE_URL: ${INTERPOL_BASE_URL:-https://ws-public.interpol.int}
      INTERPOL_FETCH_INTERVAL_SECONDS: ${INTERPOL_FETCH_INTERVAL_SECONDS:-300}
      INTERPOL_FETCH_ALL: ${INTERPOL_FETCH_ALL:-true}
      INTERPOL_FETCH_EXTENDED: ${INTERPOL_FETCH_EXTENDED:-false}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_QUEUE_NAME: ${RABBITMQ_QUEUE_NAME:-interpol_red_notices}
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      ENABLE_PASS_AGE_0_9: ${ENABLE_PASS_AGE_0_9:-true}
      ENABLE_PASS_IN_PK_1YR: ${ENABLE_PASS_IN_PK_1YR:-true}
      VERY_HIGH_NATIONALITIES_1YR: ${VERY_HIGH_NATIONALITIES_1YR:-IN,PK}
      AGE_1YR_MIN: ${AGE_1YR_MIN:-10}
      AGE_1YR_MAX: ${AGE_1YR_MAX:-99}
      REQUEST_DELAY_SECONDS: ${REQUEST_DELAY_SECONDS:-3.0}
      STATE_FILE_PATH: ${STATE_FILE_PATH:-/data/scan_state.json}
    volumes:
      - web_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f 'python -m fetcher.main' || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3

  #web servisi de kendi Dockerfile’ından build ediliyor. RabbitMQ ve PostgreSQL hazır olduktan sonra başlıyor
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: interpol_web
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: ${FLASK_ENV:-production}
      INTERPOL_BASE_URL: ${INTERPOL_BASE_URL:-https://ws-public.interpol.int}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_QUEUE_NAME: ${RABBITMQ_QUEUE_NAME:-interpol_red_notices}
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      DATABASE_URL: ${DATABASE_URL:-postgresql://interpol:interpol123@postgres:5432/interpol_db}
      DETAIL_BACKFILL_ENABLED: ${DETAIL_BACKFILL_ENABLED:-true}
      DETAIL_BACKFILL_BATCH_SIZE: ${DETAIL_BACKFILL_BATCH_SIZE:-25}
      DETAIL_BACKFILL_IDLE_SECONDS: ${DETAIL_BACKFILL_IDLE_SECONDS:-30}
      DETAIL_REQUEST_DELAY_SECONDS: ${DETAIL_REQUEST_DELAY_SECONDS:-1.5}
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
      MINIO_BUCKET: ${MINIO_BUCKET:-interpol-photos}
      MINIO_PUBLIC_URL: http://localhost:9000
 
    volumes:
      - web_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8000/api/status\")'" ]
      interval: 30s
      timeout: 5s
      retries: 3

#iki kalıcı volume tanımladım.pg_data PostgreSQL verileri için, web_data ise uygulama seviyesindeki paylaşılan dosyalar için

volumes:
  web_data:
  pg_data:
  minio_data:
